# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: false

# Setup
title:            Victor Manuel Tenorio
url:              https://vmtenorio.github.io
baseurl:          "/"

paginate:         5

# Custom vars
version:          0.1

github:
  repo:           https://github.com/vmtenorio/vmtenorio.github.io
