# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: false

# Setup
title:            Victor Manuel Tenorio's webpage
url:              https://vmtenorio.github.io
baseurl:          /vmtenorio.github.io/

paginate:         5

# Custom vars
version:          0.1

github:
  repo:           https://github.com/vmtenorio.github.io
