# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: false

# Setup
title:            Victor Manuel Tenorio
description:      PhD Student in King Juan Carlos University, Madrid. Graph Neural Networks is my main area of research.
tagline:          PhD Student in King Juan Carlos University, Madrid. Graph Neural Networks is my main area of research.
url:              https://vmtenorio.github.io
baseurl:          ""

paginate:         5

# Custom vars
version:          0.1

github:
  repo:           https://github.com/vmtenorio/vmtenorio.github.io
